// Block factory and metadata
export { createCrmBlock, crmBlockMetadata } from './lib/crm.block';
export type { CrmBlock, CrmBlockConfig } from './lib/crm.block';

// Types
export type {
  // Account types
  Account,
  AccountDetail,
  CreateAccountRequest,
  UpdateAccountRequest,
  ListAccountsParams,
  // Account Document types
  AccountDocument,
  AddAccountDocumentRequest,
  PresignDocumentRequest,
  PresignDocumentResponse,
  MultipartPresignRequest,
  MultipartPresignResponse,
  MultipartCompleteRequest,
  MultipartCompleteResponse,
  // Contact types
  Contact,
  ContactProfile,
  CreateContactRequest,
  UpdateContactRequest,
  ListContactsParams,
  // Contact Event types
  ContactEvent,
  CreateContactEventRequest,
  UpdateContactEventRequest,
  ListContactEventsParams,
  ConfirmationRequest,
  CheckinRequest,
  CheckoutRequest,
  EventNotesRequest,
  // Lead types
  Lead,
  CreateLeadRequest,
  UpdateLeadRequest,
  ListLeadsParams,
  // Lead Follow types
  LeadFollow,
  CreateLeadFollowRequest,
  UpdateLeadFollowRequest,
  ListLeadFollowsParams,
  // Opportunity types
  Opportunity,
  CreateOpportunityRequest,
  UpdateOpportunityRequest,
  ListOpportunitiesParams,
  // Meeting types
  Meeting,
  CreateMeetingRequest,
  UpdateMeetingRequest,
  ListMeetingsParams,
  // Meeting Participant types
  MeetingParticipant,
  CreateMeetingParticipantRequest,
  UpdateMeetingParticipantRequest,
  ListMeetingParticipantsParams,
  // Meeting Billing types
  MeetingBilling,
  CreateMeetingBillingRequest,
  UpdateMeetingBillingRequest,
  ListMeetingBillingsParams,
  PaymentSplit,
  EapSession,
  OutstandingByPayer,
  BillingRevenueReport,
  BillingAgingReport,
  BillingParticipantReport,
  // Quote types
  Quote,
  CreateQuoteRequest,
  UpdateQuoteRequest,
  ListQuotesParams,
  // Subscriber types
  Subscriber,
  CreateSubscriberRequest,
  UpdateSubscriberRequest,
  ListSubscribersParams,
  // Referral types
  Referral,
  CreateReferralRequest,
  UpdateReferralRequest,
  ListReferralsParams,
  // Touch types
  Touch,
  CreateTouchRequest,
  UpdateTouchRequest,
  ListTouchesParams,
  // Category types
  Category,
  AccountCategory,
  CreateCategoryRequest,
  UpdateCategoryRequest,
  ListCategoriesParams,
  AddAccountCategoryRequest,
  UpdateAccountCategoryRequest,
  // Calendar Account types
  CalendarAccount,
  CreateCalendarAccountRequest,
  UpdateCalendarAccountRequest,
  ListCalendarAccountsParams,
  SyncCalendarRequest,
  SyncCalendarResponse,
  // Busy Block types
  BusyBlock,
  CreateBusyBlockRequest,
  ListBusyBlocksParams,
  // ICS Token types
  IcsToken,
  CreateIcsTokenRequest,
  ListIcsTokensParams,
  // Zoom Meeting types
  ZoomMeeting,
  ZoomAvailability,
  ProvisionZoomMeetingRequest,
  UpdateZoomMeetingRequest,
  // Zoom Host types
  ZoomHost,
  ZoomHostAvailability,
  ZoomHostAllocation,
  AvailableUser,
  CreateZoomHostRequest,
  UpdateZoomHostRequest,
  ListZoomHostsParams,
} from './lib/types';

// Services
export type {
  AccountsService,
  ContactsService,
  ContactEventsService,
  LeadsService,
  LeadFollowsService,
  OpportunitiesService,
  MeetingsService,
  MeetingParticipantsService,
  MeetingBillingsService,
  QuotesService,
  SubscribersService,
  ReferralsService,
  TouchesService,
  CategoriesService,
  CalendarAccountsService,
  BusyBlocksService,
  IcsTokensService,
  ZoomMeetingsService,
  ZoomHostsService,
} from './lib/services';

export {
  createAccountsService,
  createContactsService,
  createContactEventsService,
  createLeadsService,
  createLeadFollowsService,
  createOpportunitiesService,
  createMeetingsService,
  createMeetingParticipantsService,
  createMeetingBillingsService,
  createQuotesService,
  createSubscribersService,
  createReferralsService,
  createTouchesService,
  createCategoriesService,
  createCalendarAccountsService,
  createBusyBlocksService,
  createIcsTokensService,
  createZoomMeetingsService,
  createZoomHostsService,
} from './lib/services';

// Mappers (for advanced use cases)
export {
  accountMapper,
  accountDetailMapper,
  accountDocumentMapper,
  contactMapper,
  contactProfileMapper,
  contactEventMapper,
  leadMapper,
  leadFollowMapper,
  opportunityMapper,
  meetingMapper,
  meetingParticipantMapper,
  meetingBillingMapper,
  quoteMapper,
  subscriberMapper,
  referralMapper,
  touchMapper,
  categoryMapper,
  accountCategoryMapper,
  calendarAccountMapper,
  busyBlockMapper,
  icsTokenMapper,
  zoomMeetingMapper,
  zoomHostMapper,
} from './lib/mappers';
