import type { ResourceMapper } from '@23blocks/jsonapi-codec';
import type { Appointment } from '../types/appointment.js';
import { parseString, parseDate, parseStatus, parseOptionalNumber } from './utils.js';

export const appointmentMapper: ResourceMapper<Appointment> = {
  type: 'appointment',
  map: (resource) => ({
    id: resource.id,
    uniqueId: resource.id,
    formUniqueId: parseString(resource.attributes['form_unique_id']) ?? '',
    userUniqueId: parseString(resource.attributes['user_unique_id']),
    email: parseString(resource.attributes['email']),
    firstName: parseString(resource.attributes['first_name']),
    middleName: parseString(resource.attributes['middle_name']),
    lastName: parseString(resource.attributes['last_name']),
    phoneNumber: parseString(resource.attributes['phone_number']),
    selectedOption: parseString(resource.attributes['selected_option']),
    formFields: resource.attributes['form_fields'] as Record<string, unknown> | undefined,
    startAt: parseDate(resource.attributes['start_at']) ?? new Date(),
    endAt: parseDate(resource.attributes['end_at']),
    duration: parseOptionalNumber(resource.attributes['duration']),
    locationUniqueId: parseString(resource.attributes['location_unique_id']),
    locationName: parseString(resource.attributes['location_name']),
    locationAddress: parseString(resource.attributes['location_address']),
    assignedToUniqueId: parseString(resource.attributes['assigned_to_unique_id']),
    assignedToName: parseString(resource.attributes['assigned_to_name']),
    assignedToEmail: parseString(resource.attributes['assigned_to_email']),
    assignedToPhone: parseString(resource.attributes['assigned_to_phone']),
    notes: parseString(resource.attributes['notes']),
    source: parseString(resource.attributes['source']),
    sourceAlias: parseString(resource.attributes['source_alias']),
    sourceId: parseString(resource.attributes['source_id']),
    sourceType: parseString(resource.attributes['source_type']),
    visitorUniqueId: parseString(resource.attributes['visitor_unique_id']),
    visitorType: parseString(resource.attributes['visitor_type']),
    touchId: parseString(resource.attributes['touch_id']),
    touchReferenceId: parseString(resource.attributes['touch_reference_id']),
    status: parseStatus(resource.attributes['status']),
    confirmedAt: parseDate(resource.attributes['confirmed_at']),
    cancelledAt: parseDate(resource.attributes['cancelled_at']),
    payload: resource.attributes['payload'] as Record<string, unknown> | undefined,
    createdAt: parseDate(resource.attributes['created_at']),
    updatedAt: parseDate(resource.attributes['updated_at']),
  }),
};
