// Block factory and metadata
export { createJarvisBlock, jarvisBlockMetadata } from './lib/jarvis.block';
export type { JarvisBlock, JarvisBlockConfig } from './lib/jarvis.block';

// Types
export type {
  // Agent types
  Agent,
  CreateAgentRequest,
  UpdateAgentRequest,
  ListAgentsParams,
  ChatRequest,
  ChatResponse,
  CompleteRequest,
  CompleteResponse,
  // Prompt types
  Prompt,
  CreatePromptRequest,
  UpdatePromptRequest,
  ListPromptsParams,
  ExecutePromptRequest,
  ExecutePromptResponse,
  TestPromptRequest,
  TestPromptResponse,
  // Workflow types
  Workflow,
  WorkflowTrigger,
  CreateWorkflowRequest,
  UpdateWorkflowRequest,
  ListWorkflowsParams,
  RunWorkflowRequest,
  RunWorkflowResponse,
  // Execution types
  Execution,
  ExecutionStatus,
  ListExecutionsParams,
  // Conversation types
  Conversation,
  ConversationMessage,
  CreateConversationRequest,
  SendMessageRequest,
  SendMessageResponse,
  ListConversationsParams,
  // AI Model types
  AIModel,
  CreateAIModelRequest,
  UpdateAIModelRequest,
  ListAIModelsParams,
  // Entity types
  Entity,
  RegisterEntityRequest,
  UpdateEntityRequest,
  ListEntitiesParams,
  EntityContext,
  EntityMessage,
  CreateEntityContextRequest,
  SendEntityMessageRequest,
  SendEntityMessageResponse,
  QueryEntityFileRequest,
  QueryEntityFileResponse,
  // Cluster types
  Cluster,
  ClusterMember,
  CreateClusterRequest,
  UpdateClusterRequest,
  ListClustersParams,
  ClusterContext,
  ClusterMessage,
  CreateClusterContextRequest,
  SendClusterMessageRequest,
  SendClusterMessageResponse,
  // User types
  JarvisUser,
  RegisterJarvisUserRequest,
  UpdateJarvisUserRequest,
  ListJarvisUsersParams,
  UserContext,
  UserMessage,
  CreateUserContextRequest,
  SendUserMessageRequest,
  SendUserMessageResponse,
  UserContentContext,
  CreateUserContentContextRequest,
  // Workflow Participant types
  WorkflowParticipant,
  AddWorkflowParticipantRequest,
  UpdateWorkflowParticipantRequest,
  ListWorkflowParticipantsParams,
  // Workflow Step types
  WorkflowStep,
  AddWorkflowStepRequest,
  UpdateWorkflowStepRequest,
  AddStepPromptRequest,
  AddStepAgentRequest,
  // Workflow Instance types
  WorkflowInstance,
  WorkflowStepLog,
  WorkflowInstanceDetails,
  WorkflowStepStatus,
  StartWorkflowRequest,
  StartWorkflowResponse,
  StepWorkflowRequest,
  LogWorkflowStepRequest,
  // Agent Runtime types
  AgentThread,
  AgentRun,
  AgentMessage,
  AgentMessageContent,
  AgentContext,
  CreateAgentThreadRequest,
  CreateAgentContextRequest,
  SendAgentThreadMessageRequest,
  SendAgentThreadMessageResponse,
  SendAgentThreadMessageStreamRequest,
  RunAgentThreadRequest,
  RunAgentThreadResponse,
  AgentRunExecution,
  ListAgentRunExecutionsParams,
  // Mail Template types
  MailTemplate,
  CreateMailTemplateRequest,
  UpdateMailTemplateRequest,
  ListMailTemplatesParams,
  CreateMandrillTemplateRequest,
  UpdateMandrillTemplateRequest,
  MandrillStats,
  // Marvin Chat types
  MarvinContext,
  MarvinMessage,
  MarvinChatRequest,
  MarvinChatResponse,
  CreateMarvinContextRequest,
  SendMarvinMessageRequest,
  SendMarvinMessageResponse,
  // Comment types
  PromptComment,
  CreatePromptCommentRequest,
  UpdatePromptCommentRequest,
  ListPromptCommentsParams,
  ReplyToCommentRequest,
  ExecutionComment,
  CreateExecutionCommentRequest,
  UpdateExecutionCommentRequest,
  ListExecutionCommentsParams,
} from './lib/types';

// Services
export type {
  AgentsService,
  PromptsService,
  WorkflowsService,
  ExecutionsService,
  ConversationsService,
  AIModelsService,
  EntitiesService,
  ClustersService,
  JarvisUsersService,
  WorkflowParticipantsService,
  WorkflowStepsService,
  WorkflowInstancesService,
  AgentRuntimeService,
  MailTemplatesService,
  MarvinChatService,
  PromptCommentsService,
  ExecutionCommentsService,
} from './lib/services';

export {
  createAgentsService,
  createPromptsService,
  createWorkflowsService,
  createExecutionsService,
  createConversationsService,
  createAIModelsService,
  createEntitiesService,
  createClustersService,
  createJarvisUsersService,
  createWorkflowParticipantsService,
  createWorkflowStepsService,
  createWorkflowInstancesService,
  createAgentRuntimeService,
  createMailTemplatesService,
  createMarvinChatService,
  createPromptCommentsService,
  createExecutionCommentsService,
} from './lib/services';

// Mappers (for advanced use cases)
export {
  agentMapper,
  promptMapper,
  workflowMapper,
  executionMapper,
  conversationMapper,
  aiModelMapper,
  entityMapper,
  clusterMapper,
  jarvisUserMapper,
  workflowParticipantMapper,
  workflowStepMapper,
  workflowInstanceMapper,
  mailTemplateMapper,
  promptCommentMapper,
  executionCommentMapper,
} from './lib/mappers';
