// Block factory and metadata
export { createJarvisBlock, jarvisBlockMetadata } from './lib/jarvis.block.js';
export type { JarvisBlock, JarvisBlockConfig } from './lib/jarvis.block.js';

// Types
export type {
  // Agent types
  Agent,
  CreateAgentRequest,
  UpdateAgentRequest,
  ListAgentsParams,
  // Prompt types
  Prompt,
  CreatePromptRequest,
  UpdatePromptRequest,
  ListPromptsParams,
  ExecutePromptRequest,
  ExecutePromptResponse,
  RenderPromptRequest,
  RenderPromptResponse,
  RenderPromptMeta,
  PlaceholderValue,
  // Workflow types
  Workflow,
  CreateWorkflowRequest,
  UpdateWorkflowRequest,
  ListWorkflowsParams,
  // Execution types
  Execution,
  ListExecutionsParams,
  // Conversation types
  Conversation,
  ConversationMessage,
  CreateConversationRequest,
  SendMessageRequest,
  ListConversationsParams,
  // AI Model types
  AIModel,
  CreateAIModelRequest,
  UpdateAIModelRequest,
  ListAIModelsParams,
  // Entity types
  Entity,
  RegisterEntityRequest,
  UpdateEntityRequest,
  ListEntitiesParams,
  // Cluster types
  Cluster,
  CreateClusterRequest,
  UpdateClusterRequest,
  ListClustersParams,
  // User types
  JarvisUser,
  RegisterJarvisUserRequest,
  UpdateJarvisUserRequest,
  ListJarvisUsersParams,
  // Workflow Participant types
  WorkflowParticipant,
  AddWorkflowParticipantRequest,
  UpdateWorkflowParticipantRequest,
  ListWorkflowParticipantsParams,
  // Workflow Step types
  WorkflowStep,
  AddWorkflowStepRequest,
  UpdateWorkflowStepRequest,
  AddStepPromptRequest,
  AddStepAgentRequest,
  // Workflow Instance types
  WorkflowInstance,
  WorkflowStepLog,
  WorkflowInstanceDetails,
  WorkflowStepStatus,
  StartWorkflowRequest,
  StepWorkflowRequest,
  LogWorkflowStepRequest,
  // Agent Runtime types
  AgentThread,
  AgentMessage,
  AgentMessageContent,
  AgentContext,
  CreateAgentThreadRequest,
  CreateAgentContextRequest,
  SendAgentMessageRequest,
  AgentRunExecution,
  ListAgentRunExecutionsParams,
  // Mail Template types
  MailTemplate,
  CreateMailTemplateRequest,
  UpdateMailTemplateRequest,
  ListMailTemplatesParams,
  CreateMandrillTemplateRequest,
  UpdateMandrillTemplateRequest,
  // Marvin Chat types
  MarvinContext,
  MarvinMessage,
  MarvinChatRequest,
  MarvinChatResponse,
  CreateMarvinContextRequest,
  SendMarvinMessageRequest,
  SendMarvinMessageResponse,
  // Comment types
  PromptComment,
  CreatePromptCommentRequest,
  UpdatePromptCommentRequest,
  ListPromptCommentsParams,
  ReplyToCommentRequest,
  ExecutionComment,
  CreateExecutionCommentRequest,
  UpdateExecutionCommentRequest,
  ListExecutionCommentsParams,
  // Tool types
  Tool,
  CreateToolRequest,
  UpdateToolRequest,
  ListToolsParams,
  // Agent Tool types
  AgentTool,
  CreateAgentToolRequest,
  UpdateAgentToolRequest,
  ListAgentToolsParams,
  // Agent Tool Assignment types
  AgentToolAssignment,
  CreateAgentToolAssignmentRequest,
  UpdateAgentToolAssignmentRequest,
  ListAgentToolAssignmentsParams,
  // Condition types
  Condition,
  CreateConditionRequest,
  UpdateConditionRequest,
  ListConditionsParams,
  // Step Transition types
  StepTransition,
  CreateStepTransitionRequest,
  UpdateStepTransitionRequest,
  ListStepTransitionsParams,
  // Prompt Test types
  PromptTest,
  CreatePromptTestRequest,
  UpdatePromptTestRequest,
  ListPromptTestsParams,
  PromptTestResult,
  ListPromptTestResultsParams,
  PromptTestEvaluation,
  CreatePromptTestEvaluationRequest,
  CompareVersionsRequest,
  CompareVersionsResponse,
  // Agent Test types
  AgentTest,
  CreateAgentTestRequest,
  UpdateAgentTestRequest,
  ListAgentTestsParams,
  AgentTestResult,
  ListAgentTestResultsParams,
  // Prompt Template types
  PromptTemplate,
  ListPromptTemplatesParams,
  // Company Key types
  CompanyKey,
  CreateCompanyKeyRequest,
  // LLM Provider types
  LlmProvider,
  LlmProviderModel,
  LlmProviderValidation,
  // Analytics types
  AnalyticsDateRange,
  AnalyticsOverview,
  AnalyticsUsageParams,
  AnalyticsUsageItem,
  AnalyticsCostParams,
  AnalyticsCostItem,
  AnalyticsFeedback,
  AnalyticsConversations,
  AnalyticsRag,
  AnalyticsAgentItem,
  AnalyticsTrace,
} from './lib/types/index.js';

// Services
export type {
  AgentsService,
  PromptsService,
  WorkflowsService,
  ExecutionsService,
  ConversationsService,
  AIModelsService,
  EntitiesService,
  ClustersService,
  JarvisUsersService,
  WorkflowParticipantsService,
  WorkflowStepsService,
  WorkflowInstancesService,
  AgentRuntimeService,
  MailTemplatesService,
  MarvinChatService,
  PromptCommentsService,
  ExecutionCommentsService,
  ToolsService,
  AgentToolsService,
  AgentToolAssignmentsService,
  ConditionsService,
  StepTransitionsService,
  PromptTestsService,
  PromptTestEvaluationsService,
  AgentTestsService,
  PromptTemplatesService,
  CompanyKeysService,
  LlmProvidersService,
  OpenAIModel,
  VendorModel,
  AnalyticsService,
} from './lib/services/index.js';

export {
  createAgentsService,
  createPromptsService,
  createWorkflowsService,
  createExecutionsService,
  createConversationsService,
  createAIModelsService,
  createEntitiesService,
  createClustersService,
  createJarvisUsersService,
  createWorkflowParticipantsService,
  createWorkflowStepsService,
  createWorkflowInstancesService,
  createAgentRuntimeService,
  createMailTemplatesService,
  createMarvinChatService,
  createPromptCommentsService,
  createExecutionCommentsService,
  createToolsService,
  createAgentToolsService,
  createAgentToolAssignmentsService,
  createConditionsService,
  createStepTransitionsService,
  createPromptTestsService,
  createPromptTestEvaluationsService,
  createAgentTestsService,
  createPromptTemplatesService,
  createCompanyKeysService,
  createLlmProvidersService,
  createAnalyticsService,
} from './lib/services/index.js';

// Mappers (for advanced use cases)
export {
  agentMapper,
  promptMapper,
  workflowMapper,
  executionMapper,
  conversationMapper,
  aiModelMapper,
  entityMapper,
  clusterMapper,
  jarvisUserMapper,
  workflowParticipantMapper,
  workflowStepMapper,
  workflowInstanceMapper,
  mailTemplateMapper,
  promptCommentMapper,
  executionCommentMapper,
  toolMapper,
  agentToolMapper,
  agentToolAssignmentMapper,
  conditionMapper,
  stepTransitionMapper,
  promptTestMapper,
  promptTestResultMapper,
  promptTestEvaluationMapper,
  agentTestMapper,
  agentTestResultMapper,
  promptTemplateMapper,
  companyKeyMapper,
  llmProviderMapper,
  runExecutionMapper,
  openaiModelMapper,
} from './lib/mappers/index.js';
