import type { ResourceMapper } from '@23blocks/jsonapi-codec';
import type { Agent } from '../types/agent.js';
import { parseString, parseDate, parseBoolean, parseOptionalNumber } from './utils.js';

export const agentMapper: ResourceMapper<Agent> = {
  type: 'Agent',
  map: (resource) => ({
    id: resource.id,
    uniqueId: parseString(resource.attributes['unique_id']) || '',
    name: parseString(resource.attributes['name']) || '',
    description: parseString(resource.attributes['description']),
    instructions: parseString(resource.attributes['instructions']),
    provider: parseString(resource.attributes['provider']),
    model: parseString(resource.attributes['model']),
    source: parseString(resource.attributes['source']),
    sourceId: parseString(resource.attributes['source_id']),
    sourceType: parseString(resource.attributes['source_type']),
    sourceAlias: parseString(resource.attributes['source_alias']),
    contentUrl: parseString(resource.attributes['content_url']),
    imageUrl: parseString(resource.attributes['image_url']),
    videoUrl: parseString(resource.attributes['video_url']),
    agentIdentifier: parseString(resource.attributes['agent_identifier']),
    ragEnabled: resource.attributes['rag_enabled'] != null ? parseBoolean(resource.attributes['rag_enabled']) : undefined,
    contextWindow: parseOptionalNumber(resource.attributes['context_window']),
    encryptionKey: parseString(resource.attributes['encryption_key']),
    rateLimitPerHour: parseOptionalNumber(resource.attributes['rate_limit_per_hour']),
    communicationEnabled: resource.attributes['communication_enabled'] != null ? parseBoolean(resource.attributes['communication_enabled']) : undefined,
    email: parseString(resource.attributes['email']),
    emailProcessorUrl: parseString(resource.attributes['email_processor_url']),
    allowedDomains: parseString(resource.attributes['allowed_domains']),
    phoneNumber: parseString(resource.attributes['phone_number']),
    smsProcessorUrl: parseString(resource.attributes['sms_processor_url']),
    integrationServicesEnabled: resource.attributes['integration_services_enabled'] != null ? parseBoolean(resource.attributes['integration_services_enabled']) : undefined,
    webhookUrl: parseString(resource.attributes['webhook_url']),
    webhookSecret: parseString(resource.attributes['webhook_secret']),
    apiUrl: parseString(resource.attributes['api_url']),
    imEnabled: resource.attributes['im_enabled'] != null ? parseBoolean(resource.attributes['im_enabled']) : undefined,
    imAppsConfig: parseString(resource.attributes['im_apps_config']),
    supervisorEnabled: resource.attributes['supervisor_enabled'] != null ? parseBoolean(resource.attributes['supervisor_enabled']) : undefined,
    supervisorEmail: parseString(resource.attributes['supervisor_email']),
    supervisorPhoneNumber: parseString(resource.attributes['supervisor_phone_number']),
    lastActivityAt: parseDate(resource.attributes['last_activity_at']),
    totalMessagesProcessed: parseOptionalNumber(resource.attributes['total_messages_processed']),
    averageResponseTime: parseOptionalNumber(resource.attributes['average_response_time']),
    errorCount: parseOptionalNumber(resource.attributes['error_count']),
    successRate: parseOptionalNumber(resource.attributes['success_rate']),
    status: parseString(resource.attributes['status']) || 'active',
    enabled: resource.attributes['enabled'] != null ? parseBoolean(resource.attributes['enabled']) : undefined,
    createdAt: parseDate(resource.attributes['created_at']) || new Date(),
    updatedAt: parseDate(resource.attributes['updated_at']) || new Date(),
  }),
};
