import type { ResourceMapper } from '@23blocks/jsonapi-codec';
import type { FlexibleOrder } from '../types/flexible-order';
import { parseDate } from './utils';

export const flexibleOrderMapper: ResourceMapper<FlexibleOrder> = {
  type: 'flexible_order',
  map: (resource) => ({
    id: resource.id,
    uniqueId: resource.attributes?.['unique_id'] as string,
    customerUniqueId: resource.attributes?.['customer_unique_id'] as string | undefined,
    userUniqueId: resource.attributes?.['user_unique_id'] as string | undefined,
    entityUniqueId: resource.attributes?.['entity_unique_id'] as string | undefined,
    orderNumber: resource.attributes?.['order_number'] as string | undefined,
    subtotal: resource.attributes?.['subtotal'] as number,
    tax: resource.attributes?.['tax'] as number,
    tips: resource.attributes?.['tips'] as number,
    total: resource.attributes?.['total'] as number,
    currency: resource.attributes?.['currency'] as string,
    status: resource.attributes?.['status'] as string,
    details: ((resource.attributes?.['details'] as any[]) || []).map((d: any) => ({
      id: d.id,
      uniqueId: d.unique_id,
      name: d.name,
      description: d.description,
      quantity: d.quantity,
      unitPrice: d.unit_price,
      subtotal: d.subtotal,
      tax: d.tax,
      total: d.total,
      status: d.status,
      logistics: d.logistics ? {
        carrier: d.logistics.carrier,
        trackingNumber: d.logistics.tracking_number,
        trackingUrl: d.logistics.tracking_url,
        shippedAt: d.logistics.shipped_at ? parseDate(d.logistics.shipped_at) : undefined,
        deliveredAt: d.logistics.delivered_at ? parseDate(d.logistics.delivered_at) : undefined,
        estimatedDelivery: d.logistics.estimated_delivery ? parseDate(d.logistics.estimated_delivery) : undefined,
        address: d.logistics.address,
        payload: d.logistics.payload,
      } : undefined,
      payload: d.payload,
    })),
    payments: ((resource.attributes?.['payments'] as any[]) || []).map((p: any) => ({
      id: p.id,
      uniqueId: p.unique_id,
      amount: p.amount,
      currency: p.currency,
      method: p.method,
      status: p.status,
      confirmedAt: p.confirmed_at ? parseDate(p.confirmed_at) : undefined,
      payload: p.payload,
    })),
    logistics: resource.attributes?.['logistics'] ? {
      carrier: (resource.attributes?.['logistics'] as any).carrier,
      trackingNumber: (resource.attributes?.['logistics'] as any).tracking_number,
      trackingUrl: (resource.attributes?.['logistics'] as any).tracking_url,
      shippedAt: (resource.attributes?.['logistics'] as any).shipped_at ? parseDate((resource.attributes?.['logistics'] as any).shipped_at) : undefined,
      deliveredAt: (resource.attributes?.['logistics'] as any).delivered_at ? parseDate((resource.attributes?.['logistics'] as any).delivered_at) : undefined,
      estimatedDelivery: (resource.attributes?.['logistics'] as any).estimated_delivery ? parseDate((resource.attributes?.['logistics'] as any).estimated_delivery) : undefined,
      address: (resource.attributes?.['logistics'] as any).address,
      payload: (resource.attributes?.['logistics'] as any).payload,
    } : undefined,
    payload: resource.attributes?.['payload'] as Record<string, unknown> | undefined,
    createdAt: parseDate(resource.attributes?.['created_at']),
    updatedAt: parseDate(resource.attributes?.['updated_at']),
  }),
};
