import type { ResourceMapper } from '@23blocks/jsonapi-codec';
import type { Order } from '../types/order.js';
import { parseString, parseDate, parseNumber, parseOrderStatus } from './utils.js';

export const orderMapper: ResourceMapper<Order> = {
  type: 'Order',
  map: (resource) => ({
    id: resource.id,
    uniqueId: parseString(resource.attributes['unique_id']) || '',
    createdAt: parseDate(resource.attributes['created_at']) || new Date(),
    updatedAt: parseDate(resource.attributes['updated_at']) || new Date(),

    code: parseString(resource.attributes['code']),
    displayUniqueId: parseString(resource.attributes['display_unique_id']),
    parentUniqueId: parseString(resource.attributes['parent_unique_id']),
    customerUniqueId: parseString(resource.attributes['customer_unique_id']),
    customerName: parseString(resource.attributes['customer_name']),
    customerEmail: parseString(resource.attributes['customer_email']),
    customerPhone: parseString(resource.attributes['customer_phone']),
    customerNotes: parseString(resource.attributes['customer_notes']),
    status: parseOrderStatus(resource.attributes['status']),
    logisticsStatus: parseString(resource.attributes['logistics_status']),
    subtotal: parseNumber(resource.attributes['subtotal']),
    discount: parseNumber(resource.attributes['discount']),
    discountValue: parseNumber(resource.attributes['discount_value']) || undefined,
    delivery: parseNumber(resource.attributes['delivery']) || undefined,
    tax: parseNumber(resource.attributes['tax']),
    taxValue: parseNumber(resource.attributes['tax_value']) || undefined,
    fees: parseNumber(resource.attributes['fees']) || undefined,
    feesValue: parseNumber(resource.attributes['fees_value']) || undefined,
    vendorDiscount: parseNumber(resource.attributes['vendor_discount']) || undefined,
    vendorDiscountValue: parseNumber(resource.attributes['vendor_discount_value']) || undefined,
    vendorPrice: parseNumber(resource.attributes['vendor_price']) || undefined,
    openPrice: parseNumber(resource.attributes['open_price']) || undefined,
    openStock: parseNumber(resource.attributes['open_stock']) || undefined,
    total: parseNumber(resource.attributes['total']),
    balance: parseNumber(resource.attributes['balance']) || undefined,
    source: parseString(resource.attributes['source']),
    sourceAlias: parseString(resource.attributes['source_alias']),
    sourceId: parseString(resource.attributes['source_id']),
    sourceType: parseString(resource.attributes['source_type']),
    internalNotes: parseString(resource.attributes['internal_notes']),
    cartUniqueId: parseString(resource.attributes['cart_unique_id']),
    referredBy: parseString(resource.attributes['referred_by']),
    promoCode: parseString(resource.attributes['promo_code']),
    tips: parseNumber(resource.attributes['tips']) || undefined,
    tipsValue: parseNumber(resource.attributes['tips_value']) || undefined,
    paidAt: parseDate(resource.attributes['paid_at']),
    shippedAt: parseDate(resource.attributes['shipped_at']),
    deliveredAt: parseDate(resource.attributes['delivered_at']),
  }),
};
