import type { ResourceMapper } from '@23blocks/jsonapi-codec';
import type { OrderDetail } from '../types/order-detail.js';
import { parseString, parseDate, parseNumber } from './utils.js';

export const orderDetailMapper: ResourceMapper<OrderDetail> = {
  type: 'OrderDetail',
  map: (resource) => ({
    id: resource.id,
    uniqueId: parseString(resource.attributes['unique_id']) || '',
    createdAt: parseDate(resource.attributes['created_at']) || new Date(),
    updatedAt: parseDate(resource.attributes['updated_at']) || new Date(),

    orderUniqueId: parseString(resource.attributes['order_unique_id']) || '',
    source: parseString(resource.attributes['source']),
    sourceAlias: parseString(resource.attributes['source_alias']),
    sourceId: parseString(resource.attributes['source_id']),
    sourceType: parseString(resource.attributes['source_type']),
    productSku: parseString(resource.attributes['product_sku']),
    productUniqueId: parseString(resource.attributes['product_unique_id']),
    productName: parseString(resource.attributes['product_name']),
    productDescription: parseString(resource.attributes['product_description']),
    categoryName: parseString(resource.attributes['category_name']),
    isVariation: resource.attributes['is_variation'] === true || resource.attributes['is_variation'] === 'true' || undefined,
    variationSku: parseString(resource.attributes['variation_sku']),
    productSize: parseString(resource.attributes['product_size']),
    color: parseString(resource.attributes['color']),
    extraVariation: parseString(resource.attributes['extra_variation']),
    quantity: parseNumber(resource.attributes['quantity']),
    notes: parseString(resource.attributes['notes']),
    subtotal: parseNumber(resource.attributes['subtotal']),
    discount: parseNumber(resource.attributes['discount']),
    discountValue: parseNumber(resource.attributes['discount_value']) || undefined,
    tax: parseNumber(resource.attributes['tax']),
    taxValue: parseNumber(resource.attributes['tax_value']) || undefined,
    fees: parseNumber(resource.attributes['fees']) || undefined,
    feesValue: parseNumber(resource.attributes['fees_value']) || undefined,
    tips: parseNumber(resource.attributes['tips']) || undefined,
    tipsValue: parseNumber(resource.attributes['tips_value']) || undefined,
    vendorDiscount: parseNumber(resource.attributes['vendor_discount']) || undefined,
    vendorDiscountValue: parseNumber(resource.attributes['vendor_discount_value']) || undefined,
    vendorPrice: parseNumber(resource.attributes['vendor_price']) || undefined,
    total: parseNumber(resource.attributes['total']),
    cartDetailUniqueId: parseString(resource.attributes['cart_detail_unique_id']),
    referredBy: parseString(resource.attributes['referred_by']),
    promoCode: parseString(resource.attributes['promo_code']),
    orderCode: parseString(resource.attributes['order_code']),
    status: parseString(resource.attributes['status']),
    logisticsStatus: parseString(resource.attributes['logistics_status']),
  }),
};
